# Generated by Django 4.2 on 2023-04-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('tamaño', models.FloatField()),
                ('descripcion', models.TextField()),
                ('imagenes', models.ImageField(upload_to='galeria/product')),
            ],
        ),
    ]
