# Generated by Django 4.2 on 2023-04-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_products_imagenes_imagenes_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria/product'),
        ),
        migrations.AlterField(
            model_name='imagenes_producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria/product'),
        ),
    ]
