# Generated by Django 4.2 on 2023-04-25 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_products_imagen_alter_imagenes_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='products',
            name='detalles',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='imagenes_producto',
            name='imagen',
            field=models.ImageField(default=True, null=True, upload_to='galeria/product'),
        ),
        migrations.AlterField(
            model_name='imagenes_producto',
            name='producto',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='descripcion',
            field=models.TextField(default=True, help_text='Ingresa una descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='nombre_producto',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='peso',
            field=models.FloatField(default=True),
        ),
    ]
