# Generated by Django 4.2 on 2023-05-09 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_products_imagen_remove_products_tamaño_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria/product'),
        ),
        migrations.AlterField(
            model_name='imagenes_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='descripcion',
            field=models.TextField(help_text='Ingresa una descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='products',
            name='detalles',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='nombre_producto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='peso',
            field=models.FloatField(),
        ),
    ]
